add_newline = false

format = "$directory$git_branch$git_status$character"

[directory]
style = "#8a9868"
format = "[$path]($style) "
truncation_length = 3

[git_branch]
symbol = "󰊢 "
style = "#e08060"
format = "on [$symbol$branch]($style) "

[git_status]
style = "#908caa"
format = "[($all_status$ahead_behind )]($style)"

[character]
success_symbol = "[󰄾](bold #f6c177) " 
error_symbol = "[󰄾](bold #eb6f92) "
