add_newline = false

format = "$directory$git_branch$git_status$character"

[directory]
style = "#8999AA"
format = "[$path]($style) "
truncation_length = 3

[git_branch]
symbol = "󰊢 "
style = "#E0A568"
format = "on [$symbol$branch]($style) "

[git_status]
style = "#98A0AE"
format = "[($all_status$ahead_behind )]($style)"

[character]
success_symbol = "[󰄾](bold #E37B66) " 
error_symbol = "[󰄾](bold #CB886D) "
